name: edm_a100
channels:
  - pytorch
  - nvidia
dependencies:
  - python>=3.8, < 3.10  # package build failures on 3.10
  # - numpy=1.26.4
  # - numpy-base=1.26.4
  - numpy
  - numpy-base
  - click>=8.0
  - pillow>=8.3.1
  - scipy>=1.7.1
  # - pytorch=1.12.1
  - psutil
  - requests
  - tqdm
  - imageio
  - pip
  - pip:
    - imageio-ffmpeg>=0.4.3
    - pyspng
    - -r requirements.txt
